[tool.poetry]
name = "auth0-fastapi"
version = "0.1.0"
description = "Auth0 FastAPI Python SDK"
readme = "README.md"
authors = ["Snehil Kishore <snehil.kishore@okta.com>"]
license = "MIT"

# Tells Poetry to look for a package named `auth_server` under `src/`
packages = [
  { include = "auth", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.9"
auth0-server-python = { path = "../auth0_server_python" }
fastapi = "^0.115.11"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2"
pytest-cov = "^4.0"
pytest-asyncio = "^0.20.3"
pytest-mock = "^3.14.0"

[tool.pytest.ini_options]
addopts = "--cov=auth_server --cov-report=term-missing:skip-covered --cov-report=xml"

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"